name: Checking Linux clean build

on:
  push:
    paths:
      - "linux"

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - name: download zip file
      run: |
        COMMIT_NUMBER=`git rev-parse @:./linux`
        wget https://github.com/minskMedve/linux/archive/$COMMIT_NUMBER.zip
        unzip $COMMIT_NUMBER.zip
    
    - name: Install Dependencies
      shell: bash
      run: |
        ./install-deps.sh
    
    - name: build linux
      run: |
        COMMIT_NUMBER=`git rev-parse @:./linux`
        ./build-linux.sh ./linux-$COMMIT_NUMBER tinyconfig
      
