name: linux

on:
  push:
    paths:
      - "linux"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: download zip file
      run: |
        COMMIT_NUMBER=`git rev-parse @:./linux`
        wget https://github.com/minskMedve/linux/archive/$COMMIT_NUMBER.zip
        unzip $COMMIT_NUMBER.zip
      
    - name: build
      run: |
        cd linux-$COMMIT_NUMBER.zip
        ./build-linux.sh ./linux-$COMMIT_NUMBER tinyconfig
      
